name: Check Course Availability

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-courses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Run course check script
      env:
        PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        python register.py